# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Angular Build Development

on:
  workflow_dispatch:
  push:
    branches: [ "development" ]

jobs:
  build-and-deploy:
    defaults:
      run:
        working-directory: ./lsa-website

    runs-on: ubuntu-latest

    environment: 
      name: testing
    
    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./lsa-website
    - run: npm ci
    - run: npm run build -- --configuration production
  
    - name: Deploy files
      uses: SamKirkland/web-deploy@v1
      with:
        target-server: $CONTABO_SSH_IP
        remote-user: $CONTABO_SSH_USER
        private-ssh-key: ${{ secrets.CONTABO_SSH_PWD }}
        destination-path: ~/www/testing/
        source-path: ./dist/
