name: Run unit tests on PR created

on:
  workflow_dispatch:
  pull_request:
    branches: [ "development" ]

jobs:
  ng-test:
    
    defaults:
      run:
        working-directory: ./lsa-website
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./lsa-website

    - name: Confirm code builds successfully
      run: npm run build
        
    - name: Run tests
      run: npm run test:ci
