name: Testing Deployment

on:
    workflow_dispatch:
    push:
      branches:
        - test
        
jobs:    
    web-deploy:        
        name: 🎉 Deploy
        runs-on: ubuntu-latest
        steps:            
        - name: 🚚 Get latest code
          uses: actions/checkout@v4
        
        - name: 📂 Sync files
          uses: SamKirkland/FTP-Deploy-Action@v4.3.5
          with:
            local-dir: ./developer_website/
            server-dir: ./testing.iglesialasendaantigua.com/
            server: ${{secrets.FTP_SERVER}}
            username: ${{secrets.FTP_USERNAME}}
            password: ${{ secrets.FTP_PASSWORD }}
    
