name: Validate Admin Panel Changes

on:
  workflow_dispatch:
  pull_request:
    branches: [ "development" ]
    paths:
      - 'admin-panel/**'

jobs:
  validate:
    defaults:
      run:
        working-directory: ./admin-panel
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./admin-panel

    - name: Install packages
      run: npm ci

    - name: Confirm code builds successfully
      run: npm run build
        
    - name: Run tests
      run: npm run test:ci
